### ISSUE TITLE
'render-before' hook deletes entire public directory

### ISSUE THREAD

**Issue by tjsturos** [m2sd/nuxt-laravel#3]
In `module.js` on line 125, this code is run:
`fs_extra_1.default.removeSync(config.output.dest);`

But the problem is that by default config.output.dest is set to `public/` which can be verified by logging the variable.

I believe that the output should be only removing the nuxt output directory, as laravel has it's `index.php` files that are required to be in the `public` directory.

I have tried to move the `index.php` file to the `static/` directory, but it does not copy the files for the development server and the laravel server cannot launch as the `public/' directory no longer exists.

**Comment by tjsturos** [comment]
It appears that the comparison a few lines above that tries to see if the output (`config.output.dest`) is not the same as the laravel public directory, but doesn't work for if you have the `router` property in your `nuxt.config.js` file and want to have the root as the base of your application.

Looking at the following, it appears to be a problem with resolving the paths:

For config.laravel.public:
`public: path_1.default.resolve(laravelRoot, options.publicDir || 'public')` 

For config.output.dest:
```
const routerBase = (nuxtOptions.router && nuxtOptions.router.base) || '/';
...
dest: path_1.default.join(laravel.public, routerBase),`
...
```
The problem is with the different methods:resolve vs join.  If you use `resolve`, then it removes the trailing slash(es) whereas `join` will leave them on.  

This will remove the public directory if the intended root directory is the root directory ('/').

**Comment by mentAl-maZe** [comment]
Hi,
sry for the late response, i have been away over new years and since i'm back i have been swamped with work.
I realize now that i never tested with the `nuxtConfig.router.app` unset...
I did consider the case but i must have made a mistake in the condition which is supposed to prevent deletion...

**Comment by mentAl-maZe** [comment]
I fix the issue right away as it was 'just' an inverse condition.
The join is intended because i want the trailing slash, so that in the condition for deletion i can check if the output folder is at the root of public or if it is further up.
In the condition for the deletion i practically remove the resolved `config.laravel.public` path from the resolved `config.output.dest` path, to get an absolute path inside laravels public folder.
sadly i had the to config values mixed up so the replace did not work because `config.output.dest` always is longer than (and therefore not contained in) `config.laravel.public`.
I realize that i took my sweet time to address this, for which i am really sorry, but i would appreciate if you could close the issue if this resolves your problem.
