### ISSUE TITLE
Rendering everything to one JS file

### ISSUE THREAD

**Issue by jbnv** [m2sd/nuxt-laravel#7]
I'm adding Nuxt to an existing Laravel application that has its own HTML layout template and currently expects one JS file. Currently the application uses Laravel Mix to compile everything to one JS file and write the JS assets to the `public` folder. Laravel takes care of the rest.

How do I configure nuxt-laravel to do the same thing? It would suffice to deploy the compiled JS files in such a way that I can find them from Laravel and add them to my template. Thanks.

**Comment by mentAl-maZe** [comment]
Hi there,

I'm not quite sure `nuxt-laravel` is the right solution for your use case.
Nuxt is a frontend framework and aims to provide a full HTML template (not just JS).
I wrote `nuxt-laravel` as an ALTERNATIVE to blade templates.
Use the `NuxtRoute` helper from [`m2s/laravel-nuxt`](https://github.com/m2sd/laravel-nuxt) to tell laravel to replace a page with content from a generated nuxt template.
That said, if you want to inject generated code into your blade template, there is a way to achieve that.
Maybe I'll include something to allow this in v5 of this module.

> BE AWARE: I have never tried this myself, this is just a primer, if you want to experiment with it

You'll have to trick Nuxt into rendering a PHP file instead of an HTML template:
1. [Customize the app template](https://nuxtjs.org/guide/views#app-template) so it looks like a PHP file.
   Create an `app.html` in you nuxt source folder, which looks something like this
   ```php
   <?php
   return [
     'html_attrs' => '{{ HTML_ATTRS }}',
     'head_attrs' => '{{ HEAD_ATTRS }}',
     'head' => <<<'HEAD'
   {{ HEAD }}
   HEAD,
     'body_attrs' => '{{ BODY_ATTRS }}',
     'app' => <<<'APP'
   {{ APP }}
   APP,
   ];
   ```
2. Rename the generated `index.html` to something like `nuxtApp.php` and put it into your storage folder (e.g. `/storage/app/nuxtApp.php`)
3. In you base layout/page blade file inject the code generated by nuxt by including the newly minted `nuxtApp.php`
   ```blade
   @php
   $nuxt = include storage_path('app/nuxtApp.php');
   @endphp
   <!DOCTYPE html>
   <html {{ $nuxt['html_attrs'] }}>
       <head {{ $nuxt['head_attrs'] }}>
           {!! $nuxt['head'] !!}
       </head>
       <body {{ $nuxt['body_attrs'] }}>
           {!! $nuxt['app'] !!}
       </body>
   </html>
   ```
4. Last but not least: inject the `initial` JS files from the nuxt build folders server manifest (Default location: `<nuxtRoot>/.nuxt/dist/server/client.manifest.json`) into the template with `<script />` tags.

If you decide to try it out let me know how it goes, otherwise please close this issue.

**Comment by jbnv** [comment]
After about a month of trying a different approach, I'm back with nuxt-laravel. And I realize what I was doing wrong here. So this particular issue is moot.
